### ISSUE TITLE
Add SMTP Incoming Support

### ISSUE THREAD

**Issue by keithnet** [linuxserver/docker-healthchecks#100]
Please add SMTPD support like the official release: 
https://github.com/healthchecks/healthchecks/commit/7912f1e4df52a91b88d72081a6ed351caa41ea86

**Comment by marcogiorgio** [comment]
There is a PR already open since March 2021... https://github.com/linuxserver/docker-healthchecks/pull/64
I don't think this image is maintained anymore

**Comment by keithnet** [comment]
For whoever this helps, I easily switched to official docker which works great. (This is on ubuntu.) I had to change permissions of files on the host: chown lxd:docker *

Here's the docker-compose.yml

Key differences from official docker-compose from dockerhub are including volumes and mapping DB to /config/hc.sqlite

version: "2.1"
services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    environment:

      - ALLOWED_HOSTS=*
      - APPRISE_ENABLED=False
      - DB=sqlite
      - DB_CONN_MAX_AGE=0
      - DB_HOST=
      - DB_NAME=/config/hc.sqlite
      - DB_PASSWORD=
      - DB_PORT=
      - DB_SSLMODE=
      - DB_TARGET_SESSION_ATTRS=
      - DB_USER=
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=hc@localhost
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - EMAIL_HOST=smartsmtphosthere
      - EMAIL_HOST_PASSWORD=
      - EMAIL_HOST_USER=
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
      - EMAIL_USE_VERIFICATION=True
      - INTEGRATIONS_ALLOW_PRIVATE_IPS=False
      - LINENOTIFY_CLIENT_ID=
      - LINENOTIFY_CLIENT_SECRET=
      - MASTER_BADGE_LABEL=Mychecks
      - MATRIX_ACCESS_TOKEN=
      - MATRIX_HOMESERVER=
      - MATRIX_USER_ID=
      - MATTERMOST_ENABLED=True
      - MSTEAMS_ENABLED=True
      - OPSGENIE_ENABLED=True
      - PAGERTREE_ENABLED=True
      - PD_APP_ID=
      - PD_ENABLED=True
      - PING_BODY_LIMIT=10000
      - PING_EMAIL_DOMAIN=localhost
      - PING_ENDPOINT=http://localhost:8000/ping/
      - PROMETHEUS_ENABLED=True
      - PUSHBULLET_CLIENT_ID=
      - PUSHBULLET_CLIENT_SECRET=
      - PUSHOVER_API_TOKEN=
      - PUSHOVER_EMERGENCY_EXPIRATION=86400
      - PUSHOVER_EMERGENCY_RETRY_DELAY=300
      - PUSHOVER_SUBSCRIPTION_URL=
      - REGISTRATION_OPEN=True
      - REMOTE_USER_HEADER=
      - RP_ID=
      - S3_ACCESS_KEY=
      - S3_BUCKET=
      - S3_ENDPOINT=
      - S3_REGION=
      - S3_SECRET_KEY=
      - S3_TIMEOUT=60
      - SECRET_KEY=----
      - SHELL_ENABLED=False
      - SIGNAL_CLI_SOCKET=
      - SITE_LOGO_URL=
      - SITE_NAME=Health Checks
      - SITE_ROOT=https://localhost:8000
      - SLACK_CLIENT_ID=
      - SLACK_CLIENT_SECRET=
      - SLACK_ENABLED=True
      - SPIKE_ENABLED=True
      - TELEGRAM_BOT_NAME=ExampleBot
      - TELEGRAM_TOKEN=
      - TRELLO_APP_KEY=
      - TWILIO_ACCOUNT=
      - TWILIO_AUTH=
      - TWILIO_FROM=
      - TWILIO_USE_WHATSAPP=False
      - USE_PAYMENTS=False
      - VICTOROPS_ENABLED=True
      - WEBHOOKS_ENABLED=True
      - ZULIP_ENABLED=True
    volumes:
      - /opt/healthchecks/_data:/config
    ports:
      - 8000:8000
      - 25:25
    restart: unless-stopped

**Comment by marcogiorgio** [comment]
> For whoever this helps, I easily switched to official docker which works great. (This is on ubuntu.) I had to change permissions of files on the host: chown lxd:docker *
> 
> Here's the docker-compose.yml
> 
> Key differences from official docker-compose from dockerhub are including volumes and mapping DB to /config/hc.sqlite
> 
> version: "2.1" services: healthchecks: image: healthchecks/healthchecks:latest container_name: healthchecks environment:
> 
> ```
>   - ALLOWED_HOSTS=*
>   - APPRISE_ENABLED=False
>   - DB=sqlite
>   - DB_CONN_MAX_AGE=0
>   - DB_HOST=
>   - DB_NAME=/config/hc.sqlite
>   - DB_PASSWORD=
>   - DB_PORT=
>   - DB_SSLMODE=
>   - DB_TARGET_SESSION_ATTRS=
>   - DB_USER=
>   - DEBUG=False
>   - DEFAULT_FROM_EMAIL=hc@localhost
>   - DISCORD_CLIENT_ID=
>   - DISCORD_CLIENT_SECRET=
>   - EMAIL_HOST=smartsmtphosthere
>   - EMAIL_HOST_PASSWORD=
>   - EMAIL_HOST_USER=
>   - EMAIL_PORT=25
>   - EMAIL_USE_TLS=False
>   - EMAIL_USE_VERIFICATION=True
>   - INTEGRATIONS_ALLOW_PRIVATE_IPS=False
>   - LINENOTIFY_CLIENT_ID=
>   - LINENOTIFY_CLIENT_SECRET=
>   - MASTER_BADGE_LABEL=Mychecks
>   - MATRIX_ACCESS_TOKEN=
>   - MATRIX_HOMESERVER=
>   - MATRIX_USER_ID=
>   - MATTERMOST_ENABLED=True
>   - MSTEAMS_ENABLED=True
>   - OPSGENIE_ENABLED=True
>   - PAGERTREE_ENABLED=True
>   - PD_APP_ID=
>   - PD_ENABLED=True
>   - PING_BODY_LIMIT=10000
>   - PING_EMAIL_DOMAIN=localhost
>   - PING_ENDPOINT=http://localhost:8000/ping/
>   - PROMETHEUS_ENABLED=True
>   - PUSHBULLET_CLIENT_ID=
>   - PUSHBULLET_CLIENT_SECRET=
>   - PUSHOVER_API_TOKEN=
>   - PUSHOVER_EMERGENCY_EXPIRATION=86400
>   - PUSHOVER_EMERGENCY_RETRY_DELAY=300
>   - PUSHOVER_SUBSCRIPTION_URL=
>   - REGISTRATION_OPEN=True
>   - REMOTE_USER_HEADER=
>   - RP_ID=
>   - S3_ACCESS_KEY=
>   - S3_BUCKET=
>   - S3_ENDPOINT=
>   - S3_REGION=
>   - S3_SECRET_KEY=
>   - S3_TIMEOUT=60
>   - SECRET_KEY=----
>   - SHELL_ENABLED=False
>   - SIGNAL_CLI_SOCKET=
>   - SITE_LOGO_URL=
>   - SITE_NAME=Health Checks
>   - SITE_ROOT=https://localhost:8000
>   - SLACK_CLIENT_ID=
>   - SLACK_CLIENT_SECRET=
>   - SLACK_ENABLED=True
>   - SPIKE_ENABLED=True
>   - TELEGRAM_BOT_NAME=ExampleBot
>   - TELEGRAM_TOKEN=
>   - TRELLO_APP_KEY=
>   - TWILIO_ACCOUNT=
>   - TWILIO_AUTH=
>   - TWILIO_FROM=
>   - TWILIO_USE_WHATSAPP=False
>   - USE_PAYMENTS=False
>   - VICTOROPS_ENABLED=True
>   - WEBHOOKS_ENABLED=True
>   - ZULIP_ENABLED=True
> volumes:
>   - /opt/healthchecks/_data:/config
> ports:
>   - 8000:8000
>   - 25:25
> restart: unless-stopped
> ```

Thanks for the info, in the official site this was not stated anywhere, I thought that I had to build the image myself.
