### ISSUE TITLE
Unable to run under Raspberry Pi 2. s6-applyuidgid: fatal error.

### ISSUE THREAD

**Issue by UniverseXXX** [linuxserver/docker-healthchecks#13]
Unable to run container under Raspberry Pi2. Logs shows the following issue:
`s6-applyuidgid: fatal: unable to exec /usr/sbin/uwsgi: No such file or directory`
	
The same config/docker compose file working fine on Synology NAS(Intel).

Thanks.

Extended log:

>[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:
  No migrations to apply.
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-applyuidgid: fatal: unable to exec /usr/sbin/uwsgi: No such file or directory
[services.d] done.
s6-applyuidgid: fatal: unable to exec /usr/sbin/uwsgi: No such file or directory
s6-applyuidgid: fatal: unable to exec /usr/sbin/uwsgi: No such file or directory

Docker-compose file:
> version: "3.6"
services:
  HealthChecks:
    image: linuxserver/healthchecks
    container_name: HealthChecks
    network_mode:     "bridge"
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - DEBUG=False
      - SITE_ROOT=https://dsfsdfsdfs
      - SITE_NAME=Server's HealthChecks
      - DEFAULT_FROM_EMAIL=sdfsdfsdf
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=sdfsdfsdfsdf
      - EMAIL_HOST_PASSWORD=sdfsdfsdfsdf
      - EMAIL_USE_TLS=True
      - ALLOWED_HOSTS=sdfsdfsdf
      - PUSHOVER_API_TOKEN=sdfsdfsdfsdf
      - PUSHOVER_SUBSCRIPTION_URL=sdfsdfdsfsdfsdf
    volumes:
      - /Dockers/HealthChecks:/config
    ports:
      - 8020:8000
    #mem_limit: 4096m

**Comment by thelamer** [comment]
Please try the latest image there were some missing dependencies in the ARM variants.

**Comment by UniverseXXX** [comment]
> Please try the latest image there were some missing dependencies in the ARM variants.

Thanks @thelamer HealthChecks working fine now
