### ISSUE TITLE
Any hope for a new build?

### ISSUE THREAD

**Issue by ansuz07** [linuxserver/docker-healthchecks#21]
Wondering if there are any plans to update this image to include new features, like Pushover or SMS.

Thanks!

**Comment by thelamer** [comment]
I am not sure what you mean, we build and push their latest releases. 

https://github.com/healthchecks/healthchecks/releases

**Comment by j0nnymoe** [comment]
They already seem to have SMS... https://raw.githubusercontent.com/healthchecks/healthchecks/master/static/img/channels.png

**Comment by ansuz07** [comment]
I'm confused then.  It looks like their latest build has SMS and Pushover support, but in the docker image I pulled yesterday I don't see either in the integrations tab.

Is there something I am missing?

**Comment by alex-phillips** [comment]
@ansuz07 All the integrations are included in our build, but their UI doesn't display the setup instructions (or the integration in the list) unless you specifically add the necessary config options to your local_settings.py file. See https://github.com/healthchecks/healthchecks/blob/master/hc/settings.py#L189 for what you need to add.
