### ISSUE TITLE
E-mails silently fail to send, enabling blocking results in 504

### ISSUE THREAD

**Issue by kidoz-yvr** [linuxserver/docker-healthchecks#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

I'm running in docker and no matter what configuration I try e-mails simply silently fail to send. I tried BLOCKING_EMAILS which resulted in the page eventually timing out when trying to send an e-mail.

Nothing appears in the logs in any case.

I've tried Mailgun, Gmail and Sendmail, all have the same result. The services have no record of receiving an e-mail from the app.

Would appreciate any help! This app looks exactly like what I want, but e-mails really need to work.

My docker-compose:

> version: "2"
> services:
>   healthchecks:
>     image: linuxserver/healthchecks
>     container_name: healthchecks
>     environment:
>       - PUID=1003
>       - PGID=1001
>       - SITE_ROOT=https://health.skyraker.ca
>       - SITE_NAME=Skyraker Health Check
>       - DEFAULT_FROM_EMAIL=<redacted>
>       - EMAIL_HOST=smtp.mailgun.org
>       - EMAIL_PORT=465
>       - EMAIL_HOST_USER=<redacted>
>       - EMAIL_HOST_PASSWORD=<redacted>
>       - EMAIL_USE_TLS=True
>       - REGISTRATION_OPEN=False
>       - DEBUG=True
>     volumes:
>       - /home/ben/healthchecks:/config
>     ports:
>       - 13005:8000
>     restart: unless-stopped

And my local_settings.py:

> EMAIL_PORT = "25" //Experimenting with other ports
> EMAIL_HOST = "smtp.mailgun.org"
> EMAIL_USE_TLS = "False" // Experimenting with configurations
> EMAIL_HOST_USER = "<redacted>"
> SITE_ROOT = "https://health.skyraker.ca"
> SITE_NAME = "Skyraker Health Check"
> DEBUG = "True"
> EMAIL_HOST_PASSWORD = "<redacted>"
> DEFAULT_FROM_EMAIL = "<redacted>"
> BLOCKING_EMAILS = "True" // Results in eventually getting a 504

Host: Linux skyraker.ca 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "./hc/lib/emails.py", line 23, in run
>     msg.send()
>   File "/usr/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
>     return self.get_connection(fail_silently).send_messages([self])
>   File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
>     new_conn_created = self.open()
>   File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
>     self.connection = self.connection_class(self.host, self.port, **connection_params)
>   File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/lib/python3.6/smtplib.py", line 338, in connect
>     (code, msg) = self.getreply()
>   File "/usr/lib/python3.6/smtplib.py", line 394, in getreply
>     raise SMTPServerDisconnected("Connection unexpectedly closed")
> smtplib.SMTPServerDisconnected: Connection unexpectedly closed

No

**Comment by kidoz-yvr** [comment]
Please note I reported this to the healthchecks project (https://github.com/healthchecks/healthchecks/issues/267) as well but the dev suggested I cross-post here.

I've also tried https://hub.docker.com/r/galexrt/healthchecks/ and had the same result.

**Comment by thelamer** [comment]
upstream issue resolved
