### ISSUE TITLE
[Feature Request] Ping via Email

### ISSUE THREAD

**Issue by joshuaavalon** [linuxserver/docker-healthchecks#26]
Healthchecks allows [pinging via Email](https://github.com/healthchecks/healthchecks#receiving-emails). But the docker does not seems to has a way to enable it. It would be nice if it have a environment variable to enable `smtpd`.

**Comment by alex-phillips** [comment]
@joshuaavalon it looks like it does have it. A fresh install's integration page has email as an option.

**Comment by joshuaavalon** [comment]
I believe that it can be set in the `local_settings.py`.

**Comment by ytzelf** [comment]
@joshuaavalon where exactly in local_settings did you enable it?
Can't find it in https://github.com/healthchecks/healthchecks/#configuration

Thanks!

**Comment by cmanzoni** [comment]
@alex-phillips is there a chance to have it enabled via variable?
It should be as simple as add 
`attach-daemon = /usr/bin/python3 ./manage.py smtpd --port 2525` to the uwsgi ini, but I'm not sure.

Thanks,
CM
