### ISSUE TITLE
[Bug] Unable to use postgres as database

### ISSUE THREAD

**Issue by joshuaavalon** [linuxserver/docker-healthchecks#27]
Problem

In the Dockerfile, `postgresql-dev` is added `build-dependencies` and removed afterward which causes 

> django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: Error loading shared library libpq.so.5: No such file or directory (needed by /usr/lib/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so)

if you set the database to postgres. I will expect similar issue to mysql.

**Comment by aptalca** [comment]
Fixed in #32
