### ISSUE TITLE
PUID/PGID Magic Not Working

### ISSUE THREAD

**Issue by tonydm** [linuxserver/docker-healthchecks#40]
## Expected Behavior
Enter container as the user abc with uid and gid as passed in docker run command

## Current Behavior
Enter container as root(0).  su to abc, still root(0)

## Steps to Reproduce
services-admin@datastore:(172.20.0.9)~/DockerServices/test$ id services-admin
uid=1001(services-admin) gid=1001(services-admin) groups=1001(services-admin),27(sudo),33(www-data),999(docker)

docker run --rm -it --name deleteme -v $PWD:/app -e PUID=`id -u $USER` -e PGID=`id -g $USER` lsiobase/ubuntu:latest /bin/bash

## Environment
Ubuntu:18.04
x86_64

**How docker service was installed:**      
apt-get remove docker docker-engine docker.io -yqq &&  apt-get update -qq

apt-get install -yqq \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
apt-get update -qq

apt-get install -yqq docker-ce

## Command used to create docker container (run/create/compose/screenshot)
docker run --rm -it --name deleteme -v $PWD:/app -e PUID=`id -u $USER` -e PGID=`id -g $USER` lsiobase/ubuntu:latest /bin/bash

## Docker logs
N/A

**Comment by gunr2171** [comment]
I think it's correct that when you first `exec` into the container you are root - the container as a whole runs as root, but the application inside runs as a lower-privileged user. The root user is needed to `chown` files and folders for persistent data during bootup.

As for the rest of the issue, like not being able to switch to the other user once inside, not sure.
