### ISSUE TITLE
Apprise Docker mod

### ISSUE THREAD

**Issue by Braincoke** [linuxserver/docker-healthchecks#46]
Hi,

I needed Apprise to be installed in the Healthchecks container so I created a [docker mod](https://github.com/Braincoke/docker-healthchecks-apprise-mod).

I'd like it to be added to the official repo or at least be mentionned in the README for other people that could be struggling with this like I did.

According to the [docs](https://github.com/linuxserver/docker-mods#submitting-a-pr-for-a-mod-to-be-added-to-the-official-linuxserverio-repo), the steps to submit a PR are:

1. Ask the team to create a new branch named <baseimagename>-<modname> in this repo. Baseimage should be the name of the image the mod will be applied to. The new branch will be based on the template branch.

[... 8 other steps]

Could you create a new branch named `docker-healthchecks-apprise-mod` so that I can continue with the process ?

**Comment by aptalca** [comment]
@Braincoke it looks good. I created a new branch: https://github.com/linuxserver/docker-mods/tree/healthchecks-apprise
You can PR there.
Thanks

**Comment by Braincoke** [comment]
Thanks I created a [PR](https://github.com/linuxserver/docker-mods/pull/46). I think I can close this now.
