### ISSUE TITLE
Changes to environment variables are not persisted to local_settings.py file

### ISSUE THREAD

**Issue by gunr2171** [linuxserver/docker-healthchecks#54]
## Expected Behavior

The documentation for this image tells me to customize the image by setting environment variables (`-e EMAIL_HOST=abcd`, etc). I can see, _on the first deployment_, that these values are inserted into the `local_settings.py` file, which is saved to wherever I volumed the `/config` folder.

That's all well and good. But let's say down the line I want to change, for example, my SMTP password.

Again, taking the documentation into consideration, I'd expect that all I'd need to do is (I'm using a docker-compose file) modify the environment variable values in the compose file and run `docker-compose up -d`.

## Current Behavior
The `local_settings.py` file is never updated with the latest environment variable values. The application continues to use the settings from the first deployment.

If the `local_settings.py` file already exists (which because it is part of the persistent directory, it _should be_ after the first deployment), the file will not be modified during container boot-up, even if the keys in the file differ from the user provided environment variables.

This can be see from [this line](https://github.com/linuxserver/docker-healthchecks/blob/9b17203747ba3f88e015d147c603206bdf12433e/root/etc/cont-init.d/30-config#L20), which only checks if the file exists, and if yes, does nothing.

## Steps to Reproduce

1. Make a file `/tmp/hc/local_settings.py` with this content:
   ```
   EMAIL_HOST = "smtp.example.com"
   DEFAULT_FROM_EMAIL = "dude@example.com"
   BASE_URL = "hc.example.com"
   EMAIL_USE_TLS = True
   SITE_ROOT = "https://hc.example.com"
   DEBUG = False
   EMAIL_PORT = "587"
   SITE_NAME = "Example HealthChecks"
   ALLOWED_HOSTS = "*"
   EMAIL_HOST_PASSWORD = "abcdefghijk"
   EMAIL_HOST_USER = "dude@example.com"
   ALLOWED_HOSTS = ["*"]
   CSRF_TRUSTED_ORIGINS = ["hc.example.com"]
   PING_ENDPOINT = SITE_ROOT + "/ping/"
   ```
2. Run the command:
```
docker run \
  -d \
  --name=healthchecks \
  -e PUID=1000 \
  -e PGID=1000 \
  -e SITE_ROOT="new.example.com" \
  -e SITE_NAME="New Site Name" \
  -e DEFAULT_FROM_EMAIL="new@example.com" \
  -e EMAIL_HOST="newsmtp.example.com" \
  -e EMAIL_PORT="111" \
  -e EMAIL_HOST_USER="new@example.com" \
  -e EMAIL_HOST_PASSWORD="qwerty" \
  -e EMAIL_USE_TLS="True" \
  -e ALLOWED_HOSTS="*" \
  -e SUPERUSER_EMAIL="super@example.com" \
  -e SUPERUSER_PASSWORD="super_qwerty" \
  -p 8000:8000 \
  -v /tmp/hc:/config \
  linuxserver/healthchecks
```
3. Wait for the container to boot and the website to become accessible.
4. Review the contents of the `/tmp/hc/local_settings.py` file. The contents should not have changed to the new values.

## Environment
**OS:** Arch Linux
**CPU architecture:** x86_64      
**How docker service was installed:** See above command example.

**Comment by drizuid** [comment]
Remove `/tmp/hc/local_settings.py`, rm the container, and then try your docker run **without** creating local_settings.py manually, it should work. We do not overwrite settings after they're already created.

**Comment by gunr2171** [comment]
This could be just me, but the problem I have is the _communication_ of the _use_ of environment variables.

The readme tells me that I should use environment variables _as the primary method_ to configure the application. However, it doesn't mention that environment variables will be _ignored_ after the first deployment. Because I expect that docker containers are ephemeral, I would expect that simply changing my environment variables and redeploying would have the container use the new values. This process is not idempotent.

I understand that you don't want to regenerate the local_settings.py file - a user could make manual modifications to the file that the startup script would remove. That's perfectly reasonable.

But if the real way to configure the application is with this python file, why even read environment variables at all? I can manually create the local_settings.py file and provide no environment variables when creating the container, and it runs just fine.

Again, I can understand that environment variables are there as a _convenience_ to the user when generating the settings file _for the first time_. The real problem I see here is that by telling people to use environment variables _as the primary way_ to configure the app, it will mislead them into thinking that those values can be used to then _update_ the configuration.

Ways I could think of solving this:

* Advertise in the readme file that environment variables are used _only_ for _first time_ generation of the settings file. Any future modification of the application's configs must be made manually to the settings file.
* Drop the use of environment variables and update the readme file to explain the format of the local_settings.py file that is needed.
* Regenerate the local_settings,py file on startup if and only if the environment variable `REGENERATE_SETTINGS` is true.

**Comment by gunr2171** [comment]
I've created a pull request for option 3.

**Comment by gunr2171** [comment]
Any chance my PR can get reviewed? @drizuid
