### ISSUE TITLE
Container timezone causes wrong time attributes from API

### ISSUE THREAD

**Issue by Tooa** [linuxserver/docker-healthchecks#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
* **When** I'm in the Europe/Berlin timezone
* **and** I query the API via `curl -X GET --header "X-Api-Key: <token>" http://<instance:port>/api/v1/checks/<uuid>`
* **then** I expect the `last_ping` attribute to be in the Europe/Berlin timezone

## Current Behavior
* `last_ping` attribute from does not return time in my timezone (i.e. is one hour off)

## Steps to Reproduce

1. Start Container
2. Configure check
3. Create API token
4. Query check via `curl -X GET --header "X-Api-Key: <token>" http://<instance:port>/api/v1/checks/<uuid>`

## Discussion and proposed solution

* I assume the API uses the timezone set in the container
* I propose to add an environment variable `TZ=Europe/Berlin` that allows to change the timezone of the container

## Environment
**OS:** RaspberryPI OS
**CPU architecture:** arm32
**How docker service was installed:** from the official docker repo

**Comment by aptalca** [comment]
Upstream issue: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12057#note_124235

**Comment by aptalca** [comment]
This was fixed upstream
