### ISSUE TITLE
Symlink /usr/bin/python to /usr/bin/python3

### ISSUE THREAD

**Issue by nbvcxz** [linuxserver/docker-healthchecks#66]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Application **manage.py** doesn't work due to python not recognition. The simple solution is to symlink /usr/bin/python to /usr/bin/python3 `ln -s /usr/bin/python3 /usr/bin/python` in Dockerfile.

------------------------------

## Expected Behavior
```
~$ docker exec -it healthchecks /app/healthchecks/manage.py
Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:
…
```

## Current Behavior
```
~$ docker exec -it healthchecks /app/healthchecks/manage.py
env: ‘python’: No such file or directory
```

## Steps to Reproduce
Try to run **manage.py** subcommand from official _linuxserver/healthchecks_ image

## Environment
**OS:** Alpine Linux 3.13
**CPU architecture:** x86_64
**How docker service was installed:** latest from official repo _linuxserver/healthchecks_

**Comment by Robert-turbo** [comment]
@nbvcxz  I did manage to execute `manage.py` by:

```bash
docker exec -it healthchecks bash
ln -s /usr/bin/python3 /usr/bin/python
/app/healthchecks/manage.py
```
