### ISSUE TITLE
Unable to add HTTP_COOKIE due to uwsgi buffer size 

### ISSUE THREAD

**Issue by Manuel5cc** [linuxserver/docker-healthchecks#67]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Checks can be created normally.

## Current Behavior

When trying to add a check the browser returns ERR_EMPTY RESPONSE and the log warns about buffer size. I've tried increasing it repeatedly in /etc/uwsgi/uwsgi.ini with no effects.

## Steps to Reproduce

1. Create the docker container with the default settings
2. Access the webui
3. Create a check

## Environment
**OS:** Raspbian Buster / Docker version 20.10.7, build f0df350
**CPU architecture:** arm32
**How docker service was installed:** Official docker repo

## Command used to create docker container (run/create/compose/screenshot)

docker run -d \
  --name=healthchecks \
  -e PUID=1000 \
  -e PGID=1000 \
  -e SITE_ROOT=<SITE_ROOT> \
  -e SITE_NAME=<SITE_NAME> \
  -e DEFAULT_FROM_EMAIL=<DEFAULT_FROM_EMAIL> \
  -e EMAIL_HOST=<EMAIL_HOST> \
  -e EMAIL_PORT=<EMAIL_PORT> \
  -e EMAIL_HOST_USER=<EMAIL_HOST_USER> \
  -e EMAIL_HOST_PASSWORD=<EMAIL_HOST_PASSWORD> \
  -e EMAIL_USE_TLS=<True or False> \
  -e ALLOWED_HOSTS=<ALLOWED_HOSTS> \
  -e SUPERUSER_EMAIL=<SUPERUSER_EMAIL> \
  -e SUPERUSER_PASSWORD=<SUPERUSER_PASSWORD> \
  -e REGENERATE_SETTINGS=True/False \
  -p 8000:8000 \
  -v <path to data on host>:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/healthchecks

## Docker logs

[WARNING] unable to add HTTP_COOKIE=meye_password_hash=523b8e06f956be1ee7b024b1dfeddd21a2322d6a; meye_username=admin; organizrLanguage=en; ys-torrentGrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Aqueue%25255Ewidth%25253Dn%2525253A30%255Eo%25253Aid%25253Ds%2525253Aname%25255Ewidth%25253Dn%2525253A436%255Eo%25253Aid%25253Dn%2525253A2%25255Ewidth%25253Dn%2525253A75%255Eo%25253Aid%25253Dn%2525253A3%25255Ewidth%25253Dn%2525253A150%255Eo%25253Aid%25253Dn%2525253A4%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Dn%2525253A5%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Dn%2525253A6%25255Ewidth%25253Dn%2525253A80%255Eo%25253Aid%25253Dn%2525253A7%25255Ewidth%25253Dn%2525253A80%255Eo%25253Aid%25253Dn%2525253A8%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Dn%2525253A9%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A10%25255Ewidth%25253Dn%2525253A60%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A11%25255Ewidth%25253Dn%2525253A80%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A12%25255Ewidth%25253Dn%2525253A80%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A13%25255Ewidth%25253Dn%2525253A80%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A14%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A15%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A16%25255Ewidth%25253Dn%2525253A80%255Eo%25253Aid%25253Dn%2525253A17%25255Ewidth%25253Dn%2525253A80%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A18%25255Ewidth%25253Dn%2525253A80%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A19%25255Ewidth%25253Dn%2525253A75%255Eo%25253Aid%25253Dn%2525253A20%25255Ewidth%25253Dn%2525253A75%255Eo%25253Aid%25253Dn%2525253A21%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A22%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A23%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A24%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A25%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A26%25255Ewidth%25253Dn%2525253A100; remember_token=1|5b19e19784a1bedfdeb9c712175110384e3338fb6517c61f15a0121cbf99b837e5781be4867abecf02b6da089c90cedaa535b7da256682ccd30e3159573ed911; pma_lang=es; Jackett=CfDJ8KPw1Nc0vuRHr-Ub9QSki59gy5CQ8n6gTLDxrKwqb1g-_GT0LhOSwgI-MMkbDz1n0L6eWpgIMKsZzp-062zDeS_Wa2kTufcnxIj-x1o6M1E-iUgrv-Wntk7JoXWM9sHTJEUUR62-dZ2cTSDVBTJJKUl3EMI_52Rz8r_xqZpCKSfjN4iB0Gsu3ctPPUsYgoR6ItOjLwktbqynvpIhHC61KU4wHmCsKZ6WJ9s3kBNqe6N0j_KT17NFmC3zS2rwz3dyFN-6qVcfCVxKZkHWP01thg0pguURw4ISZIYng-N_kqxt4qRLxTiBWMG6EflVvUSoK4LrMdpXty4-SPEky_fFeYA; pmaUser-1=%7B%22iv%22%3A%22piY%5C%2Fg0A7oywkH5BEjHy9vA%3D%3D%22%2C%22mac%22%3A%221ad8b9b15a5c7c326923c1876db536d5d87d1344%22%2C%22payload%22%3A%22%5C%2Fr8yMgBT3mMn8Xx5aXZA8w%3D%3D%22%7D; csrftoken=TKgMC4nGz5LSXJtewExso8wpBwqTMJtnAA7tnBfoco5lxrQoo5BbLWDqHvACXW1a; sessionid=zz8qqq1zq1etzn3z33k01sutalzedqbn to uwsgi packet, consider increasing buffer size

**Comment by solipsist01** [comment]
I'm using this container behind a Traefik reverse proxy and forward authentication workflow.
This increases the header sizes, and uwsgi doesn't (default) support larger then 4096.

Could you guys add the following in /app/healthchecks/uwsgi.ini

[uwsgi]
buffer-size = 32768
