### ISSUE TITLE
Debug mode always enabled

### ISSUE THREAD

**Issue by sfkpmr** [linuxserver/docker-healthchecks#87]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Debug mode is disabled by default.

## Current Behavior
Debug currently enabled from start and requires manual disabling by adding DEBUG=False to local_settings.py.

Previous issue https://github.com/linuxserver/docker-healthchecks/issues/18

## Steps to Reproduce

1. Create container with Docker Compose.
2. Run container.

Relevant part of Docker Compose:

  healthchecks:
    image: linuxserver/healthchecks:2.0.1
    container_name: healthchecks
    volumes:
      - ./healthchecks:/config
    environment:
      - SITE_ROOT=https://domain.com:8000
      - SUPERUSER_EMAIL=email
      - SUPERUSER_PASSWORD=password
    ports:
      - 8000:8000
    restart: unless-stopped

## Environment
**OS:** Fedora Server
**CPU architecture:** x64
**How docker service was installed:**

Docker repo

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d

## Docker logs

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:
  No migrations to apply.
Superuser creation skipped. Already exists.
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => static-collected
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Apr 28 19:50:47 2022] ***
compiled with version: 10.3.1 20210424 on 05 April 2021 18:18:03
os: Linux-4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021
nodename: 451eb25b67ca
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /app/healthchecks
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1311 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.9.5 (default, Nov 24 2021, 21:19:13)  [GCC 10.3.1 20210424]
Python main interpreter initialized at 0x7f4a15e57bf0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 203184 bytes (198 KB) for 1 cores
*** Operational MODE: single process ***
running "exec:/usr/bin/python3 ./manage.py collectstatic --noinput" (pre app)...
[services.d] done.

0 static files copied to '/app/healthchecks/static-collected', 314 unmodified.
running "exec:/usr/bin/python3 ./manage.py compress" (pre app)...
CommandError: Compressor is disabled. Set the COMPRESS_ENABLED setting or use --force to override.
command "/usr/bin/python3 ./manage.py compress" exited with non-zero code: 1
Thu Apr 28 19:50:48 2022 - FATAL hook failed, destroying instance
SIGINT/SIGQUIT received...killing workers...
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f4a15e57bf0 pid: 299 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 299)
spawned uWSGI worker 1 (pid: 316, cores: 1)

**Comment by 12354** [comment]
For me (lscr.io/linuxserver/healthchecks:version-v2.1) adding this to my docker-compose file works:
```
 environment:
      - DEBUG=False
```

**Comment by sfkpmr** [comment]
Yeah, the environment variable works, but does it make sense for that to be the default behaviour?

**Comment by thespad** [comment]
It's been added to the readme, but having it set to `true` is the upstream default.
