### ISSUE TITLE
Env vars might have wrong type

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [linuxserver/docker-healthchecks#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If I set `PING_BODY_LIMIT=10000` in my environment variables, [this init script here](https://github.com/linuxserver/docker-healthchecks/blob/cde5860bc4b5048bce6e85b7b05383e0832c491b/root/etc/s6-overlay/s6-rc.d/init-healthchecks-config/run#L84) converts it to a python string.

------------------------------

## Expected Behavior
The value has to be an integer, if not, python will throw an exception. But it  is stored as a string in the python file /app/healthchecks/hc/local_settings.py.

## Current Behavior
If I set `PING_BODY_LIMIT=10000` in my environment variables, [this init script here](https://github.com/linuxserver/docker-healthchecks/blob/cde5860bc4b5048bce6e85b7b05383e0832c491b/root/etc/s6-overlay/s6-rc.d/init-healthchecks-config/run#L84) converts it to a python string.

## Steps to Reproduce
1. Set `PING_BODY_LIMIT=10000` in your environment variables, generate the settings completely new (creating new container or set the setting to do that).
2. Ping one of the checks, and get the error:
```
Internal Server Error: /ping/URL
hc_1                   | Traceback (most recent call last):
hc_1                   |   File "/usr/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
hc_1                   |     response = get_response(request)
hc_1                   |   File "/usr/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
hc_1                   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
hc_1                   |   File "/usr/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
hc_1                   |     return view_func(*args, **kwargs)
hc_1                   |   File "/usr/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
hc_1                   |     response = view_func(request, *args, **kwargs)
hc_1                   |   File "/app/healthchecks/./hc/api/views.py", line 53, in ping
hc_1                   |     body = request.body[: settings.PING_BODY_LIMIT]
hc_1                   | TypeError: slice indices must be integers or None or have an __index__ method
```

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d
with this particular env var

## Docker logs
see above

**Comment by pinkworld123** [comment]
yes i also have same issue. temporary fix after first time run, i need to set - REGENERATE_SETTINGS=False in docker-compose of linuxserver. 

and manually set value without string "" in local_settings.py

**Comment by TheCataliasTNT2k** [comment]
Are issues generally ignored, or are you busy right now?

**Comment by thespad** [comment]
They're not ignored, we just have a lot of issues and not a lot of people so we have to prioritise based on severity and affected users. Bash is a pain with typing, I'll see what I can do.

**Comment by thespad** [comment]
Once [this build](https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-healthchecks/detail/PR-101/4/pipeline) is finished can you test with `lspipepr/healthchecks:v2.5-pkg-1eaf64f2-pr-101` and see if it works.

**Comment by pinkworld123** [comment]
> They're not ignored, we just have a lot of issues and not a lot of people so we have to prioritise based on severity and affected users. Bash is a pain with typing, I'll see what I can do.

Is there any way to contribute to repo? I would like to help.

**Comment by thespad** [comment]
PRs are always welcome if you think you've got something useful to add. See https://github.com/linuxserver/docker-healthchecks/blob/master/.github/CONTRIBUTING.md for specifics.

**Comment by TheCataliasTNT2k** [comment]
> They're not ignored, we just have a lot of issues and not a lot of people so we have to prioritise based on severity and affected users. Bash is a pain with typing, I'll see what I can do.

Well yes, that's ok. I asked, because in some repos, issues are generally ignored completely...
